/home/lukas/empty.c: In function ‘main’:
/home/lukas/empty.c:5: error: DIVINE ERROR: FAULT: access of size 4 at [heap* 3f8f742a 28h ddp] is 40 bytes out of bounds
/home/lukas/empty.c:5: note: [0] FATAL: memory error in userspace
/home/lukas/empty.c:5: note: backtrace:
/opt/divine/include/dios/sys/fault.hpp:118: note: void __dios::FaultBase::handler<__dios::Context>(_VM_Fault, _VM_Frame*, void (*)())
/home/lukas/empty.c:5: note: main
/opt/divine/include/dios/libc/sys/start.cpp:91: note: __dios_start
